apiVersion: apps/v1
kind: Deployment
metadata:
  name: semaphore-service-mirror
spec:
  template:
    spec:
      containers:
        - name: semaphore-service-mirror
          command:
            - /semaphore-service-mirror
            - -log-level=info
            - -target-kube-config=/etc/config/target-kube-config.yaml
            - -label-selector=mirror=true
            - -mirror-ns=sys-service-mirror
            - -svc-prefix=target
