kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-service-mirror
rules:
- apiGroups: [""]
  resources:
  - services
  - endpoints
  verbs:
    - get
    - create
    - update
    - delete
- apiGroups: ["discovery.k8s.io"]
  resources:
  - endpointslices
  verbs:
    - get
    - create
    - update
    - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-service-mirror-binding
subjects:
- kind: ServiceAccount
  name: kube-service-mirror
roleRef:
  kind: Role
  name: kube-service-mirror
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-service-mirror
